import Phaser from 'phaser';
import {installShootersTriggerMobileControls} from '../shooters-trigger-mobile-controls';
import {clearPendingArena,loadShootersProgress,saveShootersProgress} from '../shooters-trigger-state';
type Fighter={body:Phaser.GameObjects.Arc;team:'blue'|'red';hits:number;name:string;alive:boolean;x:number;y:number};type Shot={body:Phaser.GameObjects.Arc;x:number;y:number;vx:number;vy:number;team:'blue'|'red';owner?:'player'|'bot'};
export class ShootersTriggerArenaScene extends Phaser.Scene{public joystickVector=new Phaser.Math.Vector2();private p=loadShootersProgress();private player!:Fighter;private allies:Fighter[]=[];private enemies:Fighter[]=[];private shots:Shot[]=[];private covers:Phaser.Geom.Rectangle[]=[];private aim=new Phaser.Math.Vector2(1,0);private fire=false;private cd=0;private aiCd=0;private respawn=0;private controls?:()=>void;private hud!:Phaser.GameObjects.Text;private result=false;private specialButton?:Phaser.GameObjects.Text;
constructor(){super('ShootersTriggerArenaScene')}
create(){this.p=loadShootersProgress();clearPendingArena(this.p);saveShootersProgress(this.p);const w=this.scale.width,h=this.scale.height;this.cameras.main.setBackgroundColor('#6f984b');this.drawField(w,h);this.player=this.fighter(w*.25,h-90,'blue','YOU',0x2f7775);this.allies=[this.fighter(w*.25,h-180,'blue','ALLY 1',0x4f9a91),this.fighter(w*.25,h-270,'blue','ALLY 2',0x6ba99f)];this.enemies=[this.fighter(w*.75,130,'red','RIVAL 1',0xd66a3d),this.fighter(w*.75,220,'red','RIVAL 2',0xe08b55),this.fighter(w*.75,310,'red','RIVAL 3',0xa95c62)];this.hud=this.add.text(16,16,'ARENA · FIRST TO 3 KILLS',{fontFamily:'monospace',fontSize:'11px',color:'#fff4d4',backgroundColor:'#183322',padding:{left:9,right:9,top:7,bottom:7}}).setDepth(80);this.specialButton=this.add.text(w-18,18,this.p.equipment.specialOffense?'SPECIAL READY':'SPECIAL',{fontFamily:'monospace',fontSize:'9px',color:'#102018',backgroundColor:'#e8c95c',padding:{left:9,right:9,top:8,bottom:8}}).setOrigin(1,0).setDepth(80).setInteractive();this.specialButton.on('pointerdown',()=>{if(this.p.equipment.specialOffense&&!this.p.arena.specialUsed){this.p.arena.specialUsed=true;this.fire=true;this.cd=0;this.specialButton?.setText('SPECIAL USED')}});this.controls=installShootersTriggerMobileControls();this.input.keyboard?.on('keydown-E',()=>{if(this.p.equipment.specialOffense&&!this.p.arena.specialUsed){this.p.arena.specialUsed=true;this.specialButton?.setText('SPECIAL USED')}});window.dispatchEvent(new Event('admin-hub-games:game-ready'));this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.controls?.())}
fighter(x:number,y:number,team:'blue'|'red',name:string,c:number):Fighter{const b=this.add.circle(x,y,15,c).setDepth(30);this.add.text(x,y-24,name,{fontFamily:'monospace',fontSize:'7px',color:'#fff4d4'}).setOrigin(.5).setDepth(31);return {body:b,team,hits:0,name,alive:true,x,y}}
setMoveVector(x:number,y:number){this.joystickVector.set(x,y)}setAimVector(x:number,y:number){const l=Math.hypot(x,y)||1;this.aim.set(x/l,y/l)}setFireHeld(v:boolean){this.fire=v}isPhoneSession(){return window.matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0}
update(_t:number,d:number){if(this.result)return;if(this.respawn>0){this.respawn-=d;if(this.respawn<=0)this.revivePlayer();return}this.movePlayer(d);this.cd-=d;this.aiCd-=d;if(this.fire&&this.cd<=0)this.playerFire();if(this.aiCd<=0){this.aiCd=850;this.botFire();this.botTeamFire()}this.updateShots(d);this.updateHud();if(this.p.arena.teamKills>=3)this.endMatch('WIN')}
movePlayer(d:number){let x=this.joystickVector.x,y=this.joystickVector.y;if(!this.isPhoneSession()){const k=this.input.keyboard;if(k){if(k.addKey('A').isDown)x=-1;if(k.addKey('D').isDown)x=1;if(k.addKey('W').isDown)y=-1;if(k.addKey('S').isDown)y=1}}const l=Math.hypot(x,y)||1;this.player.x=Phaser.Math.Clamp(this.player.x+x/l*170*d/1000,40,this.scale.width-40);this.player.y=Phaser.Math.Clamp(this.player.y+y/l*170*d/1000,40,this.scale.height-40)}
playerFire(){this.cd=190;const bonus=this.p.equipment.shooting*2+(this.p.arena.specialUsed?5:0);this.shots.push(this.makeShot(this.player.body.x+this.aim.x*20,this.player.body.y+this.aim.y*20,this.aim.x,this.aim.y,'blue','player'));if(bonus)this.player.body.setFillStyle(0xe8c95c);}
botFire(){for(const e of this.enemies.filter(x=>x.alive)){const target=this.player;const a=Math.atan2(target.y-e.body.y,target.x-e.body.x);this.shots.push(this.makeShot(e.body.x+Math.cos(a)*18,e.body.y+Math.sin(a)*18,Math.cos(a),Math.sin(a),'red','bot'))}}
botTeamFire(){for(const a of this.allies.filter(x=>x.alive)){const e=this.enemies.find(x=>x.alive);if(!e)continue;const ang=Math.atan2(e.y-a.body.y,e.x-a.body.x);this.shots.push(this.makeShot(a.body.x+Math.cos(ang)*18,a.body.y+Math.sin(ang)*18,Math.cos(ang),Math.sin(ang),'blue','bot'))}}
makeShot(x:number,y:number,vx:number,vy:number,team:'blue'|'red',owner:'player'|'bot'):Shot{const body=this.add.circle(x,y,4,team==='blue'?0xf0dfb6:0xe8b18d).setDepth(25);return {body,x,y,vx:vx*420,vy:vy*420,team,owner}}
updateShots(d:number){for(let i=this.shots.length-1;i>=0;i--){const s=this.shots[i];s.x+=s.vx*d/1000;s.y+=s.vy*d/1000;s.body.setPosition(s.x,s.y);if(this.covers.some(c=>Phaser.Geom.Rectangle.Contains(c,s.x,s.y))){s.body.destroy();this.shots.splice(i,1);continue}const foes=s.team==='blue'?this.enemies.filter(x=>x.alive):[this.player];const hit=foes.find(f=>Phaser.Math.Distance.Between(s.x,s.y,f.body.x,f.body.y)<22);if(hit){this.resolveHit(hit,s);s.body.destroy();this.shots.splice(i,1);continue}if(s.x<0||s.x>this.scale.width||s.y<0||s.y>this.scale.height){s.body.destroy();this.shots.splice(i,1)}}}
resolveHit(f:Fighter,s:Shot){const dist=Phaser.Math.Distance.Between(s.x,s.y,f.body.x,f.body.y);if(f===this.player){if(dist<8||f.hits>=1&&dist<14){this.killPlayer();return}if(dist<14)f.hits++;else if(dist<20)f.body.setFillStyle(0xe8c95c);return}if(dist<8||dist<14&&++f.hits>=2){f.alive=false;f.body.setVisible(false);if(s.team==='blue'){if(s.owner==='player')this.p.arena.playerKills++;this.p.arena.teamKills++}return}}
killPlayer(){this.p.arena.deaths++;this.player.alive=false;this.player.body.setVisible(false);this.respawn=1100;this.hud.setText('YOU ARE OUT · RESPAWNING AT START LINE')}
revivePlayer(){this.player.alive=true;this.player.hits=0;this.player.body.setPosition(this.scale.width*.25,this.scale.height-90);this.player.x=this.player.body.x;this.player.y=this.player.body.y;this.player.body.setVisible(true)}
drawField(w:number,h:number){const g=this.add.graphics();g.fillStyle(0x78a653,1).fillRect(0,0,w,h);g.fillStyle(0xd1b46c,.22).fillRect(w*.48,0,w*.04,h);g.lineStyle(4,0xf4f1df,.45).strokeRect(24,24,w-48,h-48);g.lineStyle(3,0xf4f1df,.35).lineBetween(w*.18,h*.5,w*.82,h*.5);for(const a of [[w*.35,h*.27,120,42],[w*.65,h*.27,120,42],[w*.35,h*.66,120,42],[w*.65,h*.66,120,42]] as const){g.fillStyle(0x6b5139,1).fillRoundedRect(a[0],a[1],a[2],a[3],8);this.covers.push(new Phaser.Geom.Rectangle(a[0],a[1],a[2],a[3]))}this.add.text(w*.18,h*.5-28,'START', {fontFamily:'monospace',fontSize:'8px',color:'#fff4d4'}).setOrigin(.5);this.add.text(w*.82,h*.5-28,'START',{fontFamily:'monospace',fontSize:'8px',color:'#fff4d4'}).setOrigin(.5)}
updateHud(){this.hud.setText('ARENA · FIRST TO 3 KILLS\nTEAM '+this.p.arena.teamKills+' · YOUR KILLS '+this.p.arena.playerKills+' · DEATHS '+this.p.arena.deaths)}
endMatch(result:'WIN'|'LOSS'){if(this.result)return;this.result=true;this.p.arena.result=result;this.p.lastCoverage=['ARENA REPORT · '+result,'Team kills '+this.p.arena.teamKills+' · Your kills '+this.p.arena.playerKills+' · Deaths '+this.p.arena.deaths,'Preparation budget spent: '+this.p.equipment.spent+' credits.','Special used: '+(this.p.arena.specialUsed?'YES — its effect is now part of the match record.':'NO — the match was played without it.'),'Your training remains the long-term story. Retrain, prepare differently, and run it again.'];saveShootersProgress(this.p);this.time.delayedCall(650,()=>this.scene.start('ShootersTriggerMediaScene'))}}