import { addFieldGuide } from '../shooters-trigger-guidance';
import Phaser from 'phaser';
import {loadShootersProgress,resetShootersProgress} from '../shooters-trigger-state';
export class ShootersTriggerLobbyScene extends Phaser.Scene{
constructor(){super('ShootersTriggerLobbyScene')}
create(){const p=loadShootersProgress(String(this.registry.get('shootersTriggerPlayer')||'Player'));this.registry.set('shootersTriggerProgress',p);const w=this.scale.width,h=this.scale.height;this.cameras.main.setBackgroundColor('#6f984b');const g=this.add.graphics();g.fillStyle(0x78a653,1).fillRect(0,0,w,h);g.fillStyle(0x6a9549,1).fillRect(0,h*.62,w,h*.38);
this.add.text(24,22,'SHOOTERS TRIGGER · HOME FIELD',{fontFamily:'monospace',fontSize:'12px',fontStyle:'bold',color:'#fff4d4'});this.add.text(24,48,p.playerName+' · BUDGET '+p.budget,{fontFamily:'monospace',fontSize:'10px',color:'#e8c95c'});this.add.text(w/2,82,'TRAIN · PREPARE · COMPETE',{fontFamily:'monospace',fontSize:'12px',fontStyle:'bold',color:'#f4f1df'}).setOrigin(.5);
const cards=[['SHOOTING LOCATION','AIM · HIT QUALITY · REWARD','ShootersTriggerTrainingScene'],['EVASION CAMP','MOVE · COVER · SURVIVE','ShootersTriggerEvasionScene'],['MEDIA COVERAGE CENTER','STATS · THOUGHTS · EQUIPMENT','ShootersTriggerMediaScene'],['ARENA LOCATION','3v3 · FIRST TO 3 KILLS','ShootersTriggerArenaScene']];cards.forEach((c,i)=>{const portrait=h>w;const cw=Math.min(portrait?w*.82:(w-90)/2,390);const ch=88;const x=portrait?w/2:w/2+(i%2===0?-cw/2-10:cw/2+10);const y=portrait?150+i*90:190+Math.floor(i/2)*120;const b=this.add.rectangle(x,y,cw,ch,0x183322,.94).setStrokeStyle(2,0xe8c95c,.7).setInteractive();this.add.text(x-cw/2+16,y-14,c[0],{fontFamily:'monospace',fontSize:'11px',fontStyle:'bold',color:'#f4f1df'});this.add.text(x-cw/2+16,y+15,c[1],{fontFamily:'monospace',fontSize:'8px',color:'#bcd1b7'});b.on('pointerdown',()=>this.scene.start(c[2]))});
const reset=this.add.text(w-18,h-18,'RESET DATA',{fontFamily:'monospace',fontSize:'9px',color:'#f4f1df',backgroundColor:'#493526',padding:{left:10,right:10,top:8,bottom:8}}).setOrigin(1).setInteractive();reset.on('pointerdown',()=>{resetShootersProgress(p.playerName);this.scene.restart()});this.add.text(w/2,h-24,'WALK THE FIELD. EVERY TRAINING SESSION CHANGES THE STORY.',{fontFamily:'monospace',fontSize:'9px',color:'#fff4d4'}).setOrigin(.5); addFieldGuide(this,'SHOOTERS TRIGGER · FIELD GUIDE',['Start at Shooting Location: move, aim and fire for 60 seconds. Hit quality matters more than raw shots.','Go to Evasion Camp: survive one minute against three rivals. Use the useful side of cover and keep moving.','Visit Media Coverage Center: read what your training changed, record your pre-match thought, and spend the budget on equipment or a limited special.','Enter Arena: fight 3v3. First team to 3 kills wins. If you are eliminated, you respawn at your starting line.','After the match, read the report. Retrain, change preparation and try again. The game remembers what you actually did.']);}
}