import Phaser from 'phaser';
import {installShootersTriggerMobileControls} from '../shooters-trigger-mobile-controls';
import {clearPendingArena,loadShootersProgress,saveShootersProgress} from '../shooters-trigger-state';
import {createOffscreenSignal,updateOffscreenSignal,showShotAlert,addFieldGuide} from '../shooters-trigger-guidance';
type Fighter={body:Phaser.GameObjects.Arc;team:'blue'|'red';hits:number;name:string;alive:boolean;armed:boolean;x:number;y:number};type Shot={body:Phaser.GameObjects.Arc;x:number;y:number;vx:number;vy:number;team:'blue'|'red';owner?:'player'|'bot';kind?:'QUICK'|'STANDARD'|'PRESSURE';originX:number;originY:number};type DroppedMarker={body:Phaser.GameObjects.Rectangle;fighter:Fighter};
export class ShootersTriggerArenaScene extends Phaser.Scene{public joystickVector=new Phaser.Math.Vector2();private p=loadShootersProgress();private player!:Fighter;private allies:Fighter[]=[];private enemies:Fighter[]=[];private shots:Shot[]=[];private droppedMarkers:DroppedMarker[]=[];private covers:Phaser.Geom.Rectangle[]=[];private aim=new Phaser.Math.Vector2(1,0);private fire=false;private cd=0;private aiCd=0;private respawn=0;private controls?:()=>void;private hud!:Phaser.GameObjects.Text;private result=false;private specialButton?:Phaser.GameObjects.Text;private offscreenSignal?:ReturnType<typeof createOffscreenSignal>;
constructor(){super('ShootersTriggerArenaScene')}
create(){this.p=loadShootersProgress();clearPendingArena(this.p);saveShootersProgress(this.p);const w=this.scale.width,h=this.scale.height;this.cameras.main.setBackgroundColor('#6f984b');this.drawField(w,h);this.player=this.fighter(w*.25,h-90,'blue','YOU',0x2f7775);this.allies=[this.fighter(w*.25,h-180,'blue','ALLY 1',0x4f9a91),this.fighter(w*.25,h-270,'blue','ALLY 2',0x6ba99f)];this.enemies=[this.fighter(w*.75,130,'red','RIVAL 1',0xd66a3d),this.fighter(w*.75,220,'red','RIVAL 2',0xe08b55),this.fighter(w*.75,310,'red','RIVAL 3',0xa95c62)];this.hud=this.add.text(16,16,'ARENA · FIRST TO 3 KILLS',{fontFamily:'monospace',fontSize:'11px',color:'#fff4d4',backgroundColor:'#183322',padding:{left:9,right:9,top:7,bottom:7}}).setScrollFactor(0).setDepth(80);addFieldGuide(this,'ARENA · FIELD GUIDE',['Your team and the rivals meet across the field. The first team to 3 kills wins.','Move with the left control. Aim and fire with the right control. Keep reading the field instead of staring at the HUD.','Cover blocks paintballs by direction. Reposition when the rival angle changes.','Rival shots are telegraphed as QUICK, STANDARD or PRESSURE. If a rival leaves your screen, an edge signal points toward them.','If you are eliminated, you return at your starting line. The result report explains your kills, deaths, spending and special use.']);
this.offscreenSignal=createOffscreenSignal(this);
this.specialButton=this.add.text(w-18,18,this.p.equipment.specialOffense?'SPECIAL READY':'SPECIAL',{fontFamily:'monospace',fontSize:'9px',color:'#102018',backgroundColor:'#e8c95c',padding:{left:9,right:9,top:8,bottom:8}}).setOrigin(1,0).setDepth(80).setInteractive();this.specialButton.on('pointerdown',()=>{if(this.p.equipment.specialOffense&&!this.p.arena.specialUsed){this.p.arena.specialUsed=true;this.fire=true;this.cd=0;this.specialButton?.setText('SPECIAL USED')}});this.cameras.main.startFollow(this.player.body,true,0.12,0.12); this.cameras.main.setDeadzone(Math.min(w*.28,260),Math.min(h*.22,140)); this.cameras.main.setZoom(1.12); this.cameras.main.setBounds(0,0,w,h);
this.controls=installShootersTriggerMobileControls();this.input.keyboard?.on('keydown-E',()=>{if(this.p.equipment.specialOffense&&!this.p.arena.specialUsed){this.p.arena.specialUsed=true;this.specialButton?.setText('SPECIAL USED')}});window.dispatchEvent(new Event('admin-hub-games:game-ready'));this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.controls?.())}
fighter(x:number,y:number,team:'blue'|'red',name:string,c:number):Fighter{const b=this.add.circle(x,y,15,c).setDepth(30);this.add.text(x,y-24,name,{fontFamily:'monospace',fontSize:'7px',color:'#fff4d4'}).setOrigin(.5).setDepth(31);return {body:b,team,hits:0,name,alive:true,armed:true,x,y}}
setMoveVector(x:number,y:number){this.joystickVector.set(x,y)}setAimVector(x:number,y:number){const l=Math.hypot(x,y)||1;this.aim.set(x/l,y/l)}setFireHeld(v:boolean){this.fire=v}isPhoneSession(){return window.matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0}
update(_t:number,d:number){if(this.result)return;if(this.respawn>0){this.respawn-=d;if(this.respawn<=0)this.revivePlayer();return}this.movePlayer(d);this.updateBotRecovery(d);this.updateMarkerPickups();this.cd-=d;this.aiCd-=d;if(this.fire&&this.cd<=0)this.playerFire();if(this.aiCd<=0){this.aiCd=850;this.botFire();this.botTeamFire()}this.updateShots(d);updateOffscreenSignal(this,this.offscreenSignal!,{x:this.player.body.x,y:this.player.body.y},this.enemies.filter(e=>e.alive).map(e=>({x:e.body.x,y:e.body.y,name:e.name})));this.updateHud();if(this.p.arena.teamKills>=3)this.endMatch('WIN')}
movePlayer(d:number){let x=this.joystickVector.x,y=this.joystickVector.y;if(!this.isPhoneSession()){const k=this.input.keyboard;if(k){if(k.addKey('A').isDown)x=-1;if(k.addKey('D').isDown)x=1;if(k.addKey('W').isDown)y=-1;if(k.addKey('S').isDown)y=1}}const l=Math.hypot(x,y)||1;const nx=Phaser.Math.Clamp(this.player.body.x+x/l*170*d/1000,40,this.scale.width-40);const ny=Phaser.Math.Clamp(this.player.body.y+y/l*170*d/1000,40,this.scale.height-40);this.player.body.setPosition(nx,ny);this.player.x=nx;this.player.y=ny}
playerFire(){this.cd=190;const bonus=this.p.equipment.shooting*2+(this.p.arena.specialUsed?5:0);if(!this.player.armed)return;this.shots.push(this.makeShot(this.player.body.x+this.aim.x*20,this.player.body.y+this.aim.y*20,this.aim.x,this.aim.y,'blue','player','STANDARD'));if(bonus)this.player.body.setFillStyle(0xe8c95c);}
botFire(){for(const [index,e] of this.enemies.filter(x=>x.alive).entries()){const target=this.player;const a=Math.atan2(target.y-e.body.y,target.x-e.body.x);if(!e.armed)continue;const kind=index===0?'QUICK':index===1?'STANDARD':'PRESSURE';this.shots.push(this.makeShot(e.body.x+Math.cos(a)*18,e.body.y+Math.sin(a)*18,Math.cos(a),Math.sin(a),'red','bot',kind));const sx=e.body.x-this.player.body.x,sy=e.body.y-this.player.body.y;const dir=Math.abs(sx)>Math.abs(sy)?(sx<0?'LEFT':'RIGHT'):(sy<0?'ABOVE':'BELOW');showShotAlert(this,'INCOMING · '+kind,dir)}}
botTeamFire(){for(const a of this.allies.filter(x=>x.alive&&x.armed)){const e=this.enemies.find(x=>x.alive);if(!e)continue;const ang=Math.atan2(e.y-a.body.y,e.x-a.body.x);this.shots.push(this.makeShot(a.body.x+Math.cos(ang)*18,a.body.y+Math.sin(ang)*18,Math.cos(ang),Math.sin(ang),'blue','bot','STANDARD'))}}
makeShot(x:number,y:number,vx:number,vy:number,team:'blue'|'red',owner:'player'|'bot',kind:'QUICK'|'STANDARD'|'PRESSURE'='STANDARD'):Shot{const body=this.add.circle(x,y,4,team==='blue'?0xf0dfb6:0xe8b18d).setDepth(25);const speed=kind==='QUICK'?520:kind==='PRESSURE'?340:420;return {body,x,y,vx:vx*speed,vy:vy*speed,team,owner,kind,originX:x,originY:y}}
updateShots(d:number){for(let i=this.shots.length-1;i>=0;i--){const s=this.shots[i];s.x+=s.vx*d/1000;s.y+=s.vy*d/1000;s.body.setPosition(s.x,s.y);if(this.covers.some(c=>Phaser.Geom.Rectangle.Contains(c,s.x,s.y))){if(s.team==='red')showShotAlert(this,'COVER BLOCKED · '+(s.kind||'STANDARD'));s.body.destroy();this.shots.splice(i,1);continue}const foes=s.team==='blue'?this.enemies.filter(x=>x.alive):[this.player];const hit=foes.find(f=>Phaser.Math.Distance.Between(s.x,s.y,f.body.x,f.body.y)<22);if(hit){this.resolveHit(hit,s);s.body.destroy();this.shots.splice(i,1);continue}if(s.x<0||s.x>this.scale.width||s.y<0||s.y>this.scale.height){s.body.destroy();this.shots.splice(i,1)}}}
resolveHit(f:Fighter,s:Shot){const dist=Phaser.Math.Distance.Between(s.x,s.y,f.body.x,f.body.y);const range=Phaser.Math.Distance.Between(s.originX,s.originY,f.body.x,f.body.y);const close=range<170;const exceptional=dist<8;const center=dist<15;const damage=exceptional?4:center?(close?2.8:2):.45;if(f===this.player){if(exceptional||f.hits+damage>=3){showShotAlert(this,exceptional?'HIT · EXCEPTIONAL · ELIMINATION':'HIT · CENTER MASS · ELIMINATION');this.killPlayer();return}if(center){f.hits+=damage;showShotAlert(this,close?'HIT · CLOSE CENTER MASS':'HIT · CENTER MASS');if(Math.random()<.24)this.dropMarker(f);}else{f.body.setFillStyle(0xe8c95c);showShotAlert(this,'HIT · SCRAPE');}return}if(exceptional||f.hits+damage>=3){f.alive=false;f.body.setVisible(false);if(s.team==='blue'){if(s.owner==='player')this.p.arena.playerKills++;this.p.arena.teamKills++;showShotAlert(this,'RIVAL ELIMINATED · '+(exceptional?'EXCEPTIONAL':'CENTER MASS'));}return}if(center){f.hits+=damage;showShotAlert(this,close?'RIVAL HIT · CLOSE CENTER MASS':'RIVAL HIT · CENTER MASS');if(Math.random()<.24)this.dropMarker(f);}else{showShotAlert(this,'RIVAL SCRAPE');}}
killPlayer(){this.p.arena.deaths++;this.player.alive=false;this.player.body.setVisible(false);this.dropMarker(this.player);this.respawn=900;this.hud.setText('YOU ARE OUT · RESPAWNING AT START LINE')}
revivePlayer(){this.player.alive=true;this.player.hits=0;this.player.armed=this.droppedMarkers.every(m=>m.fighter!==this.player);this.player.body.setPosition(this.scale.width*.25,this.scale.height-90);this.player.x=this.player.body.x;this.player.y=this.player.body.y;this.player.body.setVisible(true);if(!this.player.armed){this.hud.setText('MARKER DOWN · MOVE OVER IT TO PICK IT UP')}}
drawField(w:number,h:number){const g=this.add.graphics();g.fillStyle(0x78a653,1).fillRect(0,0,w,h);g.fillStyle(0xd1b46c,.22).fillRect(w*.48,0,w*.04,h);g.lineStyle(4,0xf4f1df,.45).strokeRect(24,24,w-48,h-48);g.lineStyle(3,0xf4f1df,.35).lineBetween(w*.18,h*.5,w*.82,h*.5);for(const a of [[w*.35,h*.27,120,42],[w*.65,h*.27,120,42],[w*.35,h*.66,120,42],[w*.65,h*.66,120,42]] as const){g.fillStyle(0x6b5139,1).fillRoundedRect(a[0],a[1],a[2],a[3],8);this.covers.push(new Phaser.Geom.Rectangle(a[0],a[1],a[2],a[3]))}this.add.text(w*.18,h*.5-28,'START', {fontFamily:'monospace',fontSize:'8px',color:'#fff4d4'}).setOrigin(.5);this.add.text(w*.82,h*.5-28,'START',{fontFamily:'monospace',fontSize:'8px',color:'#fff4d4'}).setOrigin(.5)}
dropMarker(f:Fighter){if(!f.armed||this.droppedMarkers.some(m=>m.fighter===f))return;f.armed=false;const marker=this.add.rectangle(f.body.x+6,f.body.y+8,22,6,f.team==='blue'?0xd8c29a:0xf0a08b).setRotation(.25).setDepth(26);this.droppedMarkers.push({body:marker,fighter:f});showShotAlert(this,f===this.player?'MARKER DOWN · GO GET IT':'RIVAL MARKER DOWN · THEY MUST RECOVER');}
updateMarkerPickups(){for(let i=this.droppedMarkers.length-1;i>=0;i--){const m=this.droppedMarkers[i];if(!m.fighter.alive)continue;const f=m.fighter;const pickupRange=f===this.player?34:28;if(Phaser.Math.Distance.Between(f.body.x,f.body.y,m.body.x,m.body.y)<=pickupRange){f.armed=true;m.body.destroy();this.droppedMarkers.splice(i,1);if(f===this.player)showShotAlert(this,'MARKER RECOVERED · READY');}}}
updateBotRecovery(d:number){for(const f of [...this.enemies,...this.allies]){if(!f.alive||f.armed)continue;const marker=this.droppedMarkers.find(m=>m.fighter===f);if(!marker)continue;const dx=marker.body.x-f.body.x,dy=marker.body.y-f.body.y,l=Math.hypot(dx,dy)||1;const speed=105*d/1000;const nx=Phaser.Math.Clamp(f.body.x+dx/l*speed,40,this.scale.width-40);const ny=Phaser.Math.Clamp(f.body.y+dy/l*speed,40,this.scale.height-40);f.body.setPosition(nx,ny);f.x=nx;f.y=ny;}}
updateHud(){this.hud.setText('ARENA · FIRST TO 3 KILLS\nTEAM '+this.p.arena.teamKills+' · YOUR KILLS '+this.p.arena.playerKills+' · DEATHS '+this.p.arena.deaths)}
endMatch(result:'WIN'|'LOSS'){if(this.result)return;this.result=true;this.p.arena.result=result;this.p.lastCoverage=['ARENA REPORT · '+result,'Team kills '+this.p.arena.teamKills+' · Your kills '+this.p.arena.playerKills+' · Deaths '+this.p.arena.deaths,'Preparation budget spent: '+this.p.equipment.spent+' credits.','Special used: '+(this.p.arena.specialUsed?'YES — its effect is now part of the match record.':'NO — the match was played without it.'),'Your training remains the long-term story. Retrain, prepare differently, and run it again.'];saveShootersProgress(this.p);this.time.delayedCall(650,()=>this.scene.start('ShootersTriggerMediaScene'))}}