import Phaser from 'phaser';
import {installShootersTriggerMobileControls} from '../shooters-trigger-mobile-controls';
import {loadShootersProgress,finishEvasion} from '../shooters-trigger-state';
export class ShootersTriggerEvasionScene extends Phaser.Scene{
public joystickVector=new Phaser.Math.Vector2();private player!:Phaser.GameObjects.Arc;private bots:Phaser.GameObjects.Arc[]=[];private bullets:{x:number;y:number;vx:number;vy:number;body:Phaser.GameObjects.Arc}[]=[];private covers:Phaser.Geom.Rectangle[]=[];private p=loadShootersProgress();private elapsed=0;private cooldown=0;private controls?:()=>void;private hud!:Phaser.GameObjects.Text;private keys!:Record<string,Phaser.Input.Keyboard.Key>;
constructor(){super('ShootersTriggerEvasionScene')}
create(){this.p=loadShootersProgress();this.p.evasionTraining={shotsIncoming:0,misses:0,coverHits:0,scrapes:0,strongHits:0,survivedMs:0};const w=this.scale.width,h=this.scale.height;this.cameras.main.setBackgroundColor('#6f984b');this.drawField(w,h);this.player=this.add.circle(w/2,h-100,14,0xf0c47a).setDepth(20);this.bots=[this.bot(120,150,0xe06a3d),this.bot(w-120,170,0x4f7fa0),this.bot(w/2,145,0x8f5f9f)];this.hud=this.add.text(16,16,'EVASION CAMP · 60',{fontFamily:'monospace',fontSize:'11px',color:'#fff4d4',backgroundColor:'#183322',padding:{left:9,right:9,top:7,bottom:7}}).setScrollFactor(0).setDepth(50);addFieldGuide(this,'EVASION CAMP · FIELD GUIDE',['Three rivals will fire at you for one minute. Your job is to survive and learn what the field is telling you.','Move with the left control. Do not stay exposed just because you are moving. Put the useful face of a bunker or tyre stack between you and the incoming paint.','The warning tells you when a shot is coming. Read the direction, move, then check whether the shot missed or hit cover.','Your survival, cover use, hits and misses become the Evasion result shown by Media Coverage.']);this.controls=installShootersTriggerMobileControls();this.keys=this.input.keyboard!.addKeys('W,A,S,D') as Record<string,Phaser.Input.Keyboard.Key>;window.dispatchEvent(new Event('admin-hub-games:game-ready'));this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.controls?.())}
bot(x:number,y:number,c:number){const b=this.add.circle(x,y,16,c).setDepth(15);this.add.text(x,y-25,'OPP',{fontFamily:'monospace',fontSize:'7px',color:'#fff4d4'}).setOrigin(.5);return b}
setMoveVector(x:number,y:number){this.joystickVector.set(x,y)} setFireHeld(_v:boolean){} setAimVector(_x:number,_y:number){} isPhoneSession(){return window.matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0}
update(_t:number,d:number){this.elapsed+=d;this.p.evasionTraining.survivedMs=this.elapsed;let dx=this.joystickVector.x,dy=this.joystickVector.y;if(this.keys.A.isDown)dx=-1;if(this.keys.D.isDown)dx=1;if(this.keys.W.isDown)dy=-1;if(this.keys.S.isDown)dy=1;const len=Math.hypot(dx,dy)||1;this.player.x=Phaser.Math.Clamp(this.player.x+dx/len*150*d/1000,30,this.scale.width-30);this.player.y=Phaser.Math.Clamp(this.player.y+dy/len*150*d/1000,110,this.scale.height-35);this.cooldown-=d;if(this.cooldown<=0){this.cooldown=700;for(const bot of this.bots){const a=Math.atan2(this.player.y-bot.y,this.player.x-bot.x);this.p.evasionTraining.shotsIncoming++;const sx=bot.x-this.player.x,sy=bot.y-this.player.y;const dir=Math.abs(sx)>Math.abs(sy)?(sx<0?'LEFT':'RIGHT'):(sy<0?'ABOVE':'BELOW');showShotAlert(this,'INCOMING · STANDARD',dir);this.bullets.push({x:bot.x,y:bot.y,vx:Math.cos(a)*300,vy:Math.sin(a)*300,body:this.add.circle(bot.x,bot.y,4,0xf4dfb6).setDepth(12)})}}for(let i=this.bullets.length-1;i>=0;i--){const b=this.bullets[i];b.x+=b.vx*d/1000;b.y+=b.vy*d/1000;b.body.setPosition(b.x,b.y);if(this.covers.some(c=>Phaser.Geom.Rectangle.Contains(c,b.x,b.y))){this.p.evasionTraining.coverHits++;b.body.destroy();this.bullets.splice(i,1);continue}if(Phaser.Math.Distance.Between(b.x,b.y,this.player.x,this.player.y)<18){this.p.evasionTraining.strongHits++;showShotAlert(this,'HIT · TAKE COVER');b.body.destroy();this.bullets.splice(i,1);continue}if(b.x<0||b.x>this.scale.width||b.y<0||b.y>this.scale.height){this.p.evasionTraining.misses++;b.body.destroy();this.bullets.splice(i,1)}}this.hud.setText('EVASION CAMP · '+Math.max(0,60-Math.floor(this.elapsed/1000))+'s\nINCOMING '+this.p.evasionTraining.shotsIncoming+' · COVER '+this.p.evasionTraining.coverHits+' · HITS '+this.p.evasionTraining.strongHits);if(this.elapsed>=60000)this.finish()}
drawField(w:number,h:number){const g=this.add.graphics();g.fillStyle(0x78a653,1).fillRect(0,0,w,h);g.lineStyle(4,0xf4f1df,.4).strokeRect(22,90,w-44,h-125);for(const a of [[w*.18,h*.42,120,42],[w*.55,h*.35,150,48],[w*.78,h*.58,130,44],[w*.35,h*.72,150,44]] as const){g.fillStyle(0x6b5139,1).fillRoundedRect(a[0],a[1],a[2],a[3],8);this.covers.push(new Phaser.Geom.Rectangle(a[0],a[1],a[2],a[3]))}this.add.text(w/2,60,'USE THE COVER — SURVIVE ONE MINUTE',{fontFamily:'monospace',fontSize:'10px',color:'#fff4d4'}).setOrigin(.5)}
finish(){finishEvasion(this.p);this.scene.start('ShootersTriggerMediaScene')}}