export type ShooterHitBreakdown = { shots:number; misses:number; coverHits:number; scrapes:number; markerHits:number; centerMass:number; headshots:number };
export type ShooterEquipment = { shooting:number; evasion:number; specialOffense:boolean; specialDefense:boolean; spent:number };
export type ShooterProgress = { version:1; playerName:string; shooting:number; evasion:number; cover:number; discipline:number; budget:number; equipment:ShooterEquipment; shootingTraining:ShooterHitBreakdown; evasionTraining:{shotsIncoming:number;misses:number;coverHits:number;scrapes:number;strongHits:number;survivedMs:number}; opponentReadiness:[number,number,number]; preMatchThought:string; lastCoverage:string[]; arena:{playerKills:number;teamKills:number;deaths:number;result:'pending'|'WIN'|'LOSS';specialUsed:boolean}; updatedAt:number };
const KEY='admin-hub-games:shooters-trigger-progress-v1';
const fresh=(name='Player'):ShooterProgress=>({version:1,playerName:name,shooting:50,evasion:50,cover:50,discipline:50,budget:100,equipment:{shooting:0,evasion:0,specialOffense:false,specialDefense:false,spent:0},shootingTraining:{shots:0,misses:0,coverHits:0,scrapes:0,markerHits:0,centerMass:0,headshots:0},evasionTraining:{shotsIncoming:0,misses:0,coverHits:0,scrapes:0,strongHits:0,survivedMs:0},opponentReadiness:[50,50,50],preMatchThought:'I am ready to see what my training can do.',lastCoverage:['Your campaign begins at the training field.'],arena:{playerKills:0,teamKills:0,deaths:0,result:'pending',specialUsed:false},updatedAt:Date.now()});
export function loadShootersProgress(name?:string):ShooterProgress{try{const raw=localStorage.getItem(KEY);if(raw){const p=JSON.parse(raw) as ShooterProgress;return {...fresh(p.playerName||name||'Player'),...p,equipment:{...fresh().equipment,...p.equipment},arena:{...fresh().arena,...p.arena}}}}catch{}return fresh(name)}
export function saveShootersProgress(progress:ShooterProgress){progress.updatedAt=Date.now();try{localStorage.setItem(KEY,JSON.stringify(progress))}catch{}window.dispatchEvent(new CustomEvent('shooters-trigger:progress',{detail:progress}));void import('./firebase/firebase').then(({saveShootersProgress})=>saveShootersProgress(progress)).catch(()=>{})}
export function recordShooting(progress:ShooterProgress,hit:keyof ShooterHitBreakdown){progress.shootingTraining.shots++;progress.shootingTraining[hit]++;if(hit==='coverHits')progress.cover=Math.min(100,progress.cover+1.2);if(hit==='misses')progress.discipline=Math.max(0,progress.discipline-.15);const b=progress.shootingTraining;const quality=b.centerMass*2+b.headshots*4+b.markerHits*1.4+b.scrapes*.45;progress.shooting=Math.round(Math.max(0,Math.min(100,45+(b.shots?quality/b.shots:0)*28)));progress.budget+=hit==='headshots'?12:hit==='centerMass'?7:hit==='markerHits'?4:hit==='scrapes'?2:0}
export function finishShooting(progress:ShooterProgress){const b=progress.shootingTraining;const accuracy=b.shots?Math.round((b.scrapes+b.markerHits+b.centerMass+b.headshots)/b.shots*100):0;progress.lastCoverage=[`SHOOTING REPORT · ${progress.playerName}`,`Accuracy ${accuracy}% · ${b.centerMass} center-mass · ${b.headshots} exceptional hits.`,b.coverHits?`You learned where the field can stop a shot: ${b.coverHits} cover impacts.`:'You are still learning to read the field as a shooting surface.',`Training reward: ${Math.max(0,b.centerMass*7+b.headshots*12+b.markerHits*4+b.scrapes*2)} credits.`];saveShootersProgress(progress)}
export function finishEvasion(progress:ShooterProgress){const e=progress.evasionTraining;const survival=Math.min(100,e.survivedMs/600);const avoidance=e.shotsIncoming?Math.round((e.misses+e.coverHits)/e.shotsIncoming*100):0;progress.evasion=Math.round(Math.max(0,Math.min(100,40+survival*.3+avoidance*.3-e.strongHits*2)));progress.cover=Math.round(Math.max(0,Math.min(100,40+e.coverHits*4-e.scrapes*.7)));progress.budget+=Math.max(0,Math.round(survival/10)+e.coverHits*2-e.strongHits*2);progress.opponentReadiness=[Math.max(25,Math.min(85,progress.evasion+5)),Math.max(20,Math.min(80,progress.evasion)),Math.max(15,Math.min(75,progress.evasion-6))];progress.lastCoverage=['EVASION REPORT',`Survived ${Math.round(e.survivedMs/1000)}s · ${avoidance}% of incoming fire was avoided or stopped by cover.`,`Cover discipline: ${progress.cover}. Evasion readiness: ${progress.evasion}.`,`Available budget: ${progress.budget} credits.`];saveShootersProgress(progress)}
export function buyEquipment(progress:ShooterProgress,kind:'shooting'|'evasion'|'offense'|'defense'){const cost=kind==='shooting'||kind==='evasion'?60:80;if(progress.budget<cost)return false;progress.budget-=cost;progress.equipment.spent+=cost;if(kind==='shooting')progress.equipment.shooting=Math.min(2,progress.equipment.shooting+1);if(kind==='evasion')progress.equipment.evasion=Math.min(2,progress.equipment.evasion+1);if(kind==='offense')progress.equipment.specialOffense=true;if(kind==='defense')progress.equipment.specialDefense=true;saveShootersProgress(progress);return true}
export function clearPendingArena(progress:ShooterProgress){progress.arena={playerKills:0,teamKills:0,deaths:0,result:'pending',specialUsed:false}}
export function resetShootersProgress(name='Player'){const p=fresh(name);saveShootersProgress(p);return p}
